# Example parameters for DANTE = "Da Amazing NucleoTide Exposer"
# If a parameter is missing in a configuration file, it is supplied from a default file distributed with Dante in "input_data/default.yaml"
# Parameters marked as "infer" are inferred during program run (not required)
---
general:                    # General parameters
  output_dir: report        # Directory path for all results, created if it does not exist. Absolute or relative from current working directory.
  cpu: 8                    # Number of processes to use in the analysis.
  stranded: both            # Which strand(s) of reads to use. Accepted: "yes"/"reverse"/"both".
  profiler: False           # Use time profiler?
  output_all: False         # Output all reads, even pre-filtered. Warning: the output files may be quite long if turned on.
  verbosity: 1              # How verbose Dante is. Use integers 0-3.

allcall:                            # Parameters of genotypization
  param_file: miseq_params.txt      # Parameter file for genotyping. Absolute or relative from current directory.
  prob_background: 0.001            # Probability of background "noise" reads.

inputs:                       # List of input files. Each new entry starts with dash "-".
  - path: example_R1.fastq.gz # Path to a input file. Use "sys.stdin" for reading from the standard input (in that case "filetype" must be filled).
    filetype: infer           # File type of this input file. If not provided, it will be inferred from the file suffix.
    max_reads: all            # How many reads to process from this input file. Use "all" for processing of whole file.
  - path: example_R2.fastq.gz
    filetype: infer
    max_reads: all

annotation:                 # Parameters for HMM annotation
  snp_chance: 0.0005        # Probability of an SNP (Single Nucleotide Polymorphism) in reads. Estimated as 1/2000 based on the https://en.wikipedia.org/wiki/Single-nucleotide_polymorphism .
  delete_prob: 0.0001       # Probability of a deletion of a single nucleotide in reads. Estimated as 1/5 chance of a SNP.
  insert_prob: 0.0001       # Probability of an insertion of a single nucleotide in reads. Estimated as 1/5 chance of a SNP.
  max_delete_skips: 1       # Maximal size of a deletion. Longer deletions (if allowed) are internally treated as subsequent individual deletions.
  motif_frequency: 0.001    # Motif frequency, i.e. probability penalization of starting a motif. If too low (high penalization), annotation will miss sequences.

motifs:                                                                       # Parameters describing each motif. Each new entry starts with dash "-".
  - full_name: DM1                                                            # Name of a motif, required.
    description: Myotonic dystrophy type 1 (OMIM No. 160900)                  # Description of this motif.
    modules:                                                                  # Annotation modules of this motif (contains usually three "- seq" sub-elements - flanking, repetition, flanking)
      - seq: GAGGGAGGGGCCGGGTCCGCGGCCGGCGAACGGGGCTCGAAGGGTCCTTGTAGCCGGGAATG   # Left flanking region of the motif
      - seq: 5-CTG                                                            # Repetitive region of the motif
      - seq: GGGGGATCACAGACCATTTCTTTCTTTCGGCCAGGCTGAGGCCCTGACGTGGATGGGCAAACT  # Right flanking region of the motif
    prefilter:                                                                # Prefilter options for this motif
      type: SimpleFilter                                                      # Type of the filter. More in 'input_data/default.yaml'
      seq: 4-CTG                                                              # Sequence to filter for. "4-CTG" equals "CTGCTGCTGCTG"
    postfilter:                                                               # Post-filter option for this motif (can be supplied multiple times)
      - repetitions: 1,3,1                                                    # Minimum number of annotated module repetitions separated by commas, e.g. 1,3,1 means that we require 1 repetition of first module, 3 of second, and 1 of third. Supply 'no' for no filtering.
        bases: 5,10,5                                                         # Minimum number of annotated nucleotides in each module separated by commas, e.g. 5,10,5 means that we require 5 annotated nucleotides in first module, 10 in second, and 5 in third. Supply 'no' for no filtering.
        max_errors: 0.05                                                      # Maximal number of errors (SNP/insertions/deletion) in annotation. Supply 'no' for no filtering.
        max_errors_relative: True                                             # If this is True, "max_errors" is relative to the length of the read, i.e. 0.05 means, that maximum 5% of read can be errors.

  - full_name: SCA1
    description: Spinocerebellar ataxia 1 (OMIM No. 164400)
    modules:
      - seq: CTCCCAGCTGGAGGCCTATTCCACTCTGCTGGCCAACATGGGCAGTCTGAGCCAGACGCCGGGACACAAGGCTGAG
      - seq: 5-CAG
      - seq: CACCTCAGCAGGGCTCCGGGGCTCATCACCCCGGGGTCCCCCCCACCAGCCCAGCAGAACCAGT
    prefilter:
      type: SimpleFilter
      seq: 4-CAG
    postfilter:
      - repetitions: 1,3,1
        bases: 5,10,5

  - full_name: SCA2
    description: Spinocerebellar ataxia 2 (OMIM No. 183090)
    modules:
      - seq: TGTCCCCGCCCGGCGTGCGAGCCGGTGTATGGGCCCCTCACCATGTCGCTGAAGCCC
      - seq: 5-CAG
      - seq: CCGCCGCCCGCGGCTGCCAATGTCCGCAAGCCCGGCGGCAGCGGCCTTCTAGCG
    prefilter:
      type: SimpleFilter
      seq: 4-CAG
    postfilter:
      - repetitions: 1,3,1
        bases: 5,10,5

  - full_name: SCA3
    description: Spinocerebellar ataxia 3 (OMIM No. 109150)
    modules:
      - seq: TCTTTTAAGTTTTGTTTTTTAAATATACTTCACTTTTGAATGTTTCAGACAGCAGCAAAAG
      - seq: 5-CAG
      - seq: GGGGACCTATCAGGACAGAGTTCACATCCATGTGAAAGGCCAGCCACCAGTTCAGGAGCACTTGGGAGTGATCTA
    prefilter:
      type: SimpleFilter
      seq: 4-CAG
    postfilter:
      - repetitions: 1,3,1
        bases: 5,10,5

  - full_name: SCA17
    description: Spinocerebellar ataxia 17 (OMIM No. 607136)
    modules:
      - seq: CACTGGACTGACCCCACAGCCTATTCAGAACACCAATAGTCTGTCTATTTTGGAAGAGCAACAAAGG
      - seq: 3-CAG
      - seq: 3-CAA
      - seq: 8-CAG
      - seq: CAACAGCAA
      - seq: 19-CAG
      - seq: GCAGTGGCAGCTGCAGCCGTTCAGCAGTCAACGTCCCAGCAGGCAACACAGGGAACCTCAGGCCAGGCACCACAG
    prefilter:
      type: SimpleFilter
      seq: 4-CAG
    postfilter:
      - bases: 5,9,5,0,0,0,0
        repetitions: 1,3,2,0,0,0,0
        index_rep: 2
        max_errors: 0.2
        max_errors_relative: True
      - bases: 0,5,9,5,0,0,0
        repetitions: 0,2,3,2,0,0,0
        index_rep: 3
        max_errors: 0.2
        max_errors_relative: True
      - bases: 0,0,5,9,5,0,0
        repetitions: 0,0,2,3,1,0,0
        index_rep: 4
        max_errors: 0.2
        max_errors_relative: True
      - bases: 0,0,0,0,5,9,5
        repetitions: 0,0,0,0,1,3,1
        index_rep: 6
        max_errors: 0.2
        max_errors_relative: True
      - bases: 0,0,3,9,9,9,3
        repetitions: 0,0,1,3,1,3,1
        index_rep: 4
        index_rep2: 6
        max_errors: 0.2
        max_errors_relative: True

  - full_name: DRPLA
    description: Dentatorubro-pallidoluysian atrophy (OMIM No. 125370)
    modules:
      - seq: CAGGCCCCTTCCCTCCCTCTACTGGGGCCCAGTCCACCGCCCACCCACCAGTCTCAACACATCACCATCACCAC
      - seq: 5-CAG
      - seq: CATCACGGAAACTCTGGGCCCCCTCCTCCTGGAGCATTTCCCCACCCACTGGAGGGCGGTAGCTCCCACCAC
    prefilter:
      type: SimpleFilter
      seq: 4-CAG
    postfilter:
      - repetitions: 1,3,1
        bases: 5,10,5

  - full_name: HDL2
    description: Huntington disease-like 2 (OMIM No. 606438)
    modules:
      - seq: CTAAGATGCCACCGCATTCGGGGCAGAGCCGGGGCCGGAAGCCAGGGAGCTGC
      - seq: 5-CTG
      - seq: TAAGATGGTTTCTGTGCAGGGAACCTTGGCCGGCTCTGCAGCTGCCCGCCTGCCTGGACTCTCCGATATCCACTCCT
    prefilter:
      type: SimpleFilter
      seq: 4-CTG
    postfilter:
      - repetitions: 1,3,1
        bases: 5,10,5

