general:
  output_dir: report
  cpu: 10
  stranded: both # yes/reverse/both
  profiler: False

allcall:
  param_file: miseq_params.txt

inputs:
  - path: example_R1.fastq.gz
    filetype: infer
  - path: example_R2.fastq.gz
    filetype: infer

annotation:
  delete_prob: 0.0001
  insert_prob: 0.0001
  max_delete_skips: 1
  motif_frequency: 0.005
  snp_chance: 0.0005

motifs:
  - full_name: DMPK
    description: Dystrophia Myotonica Protein Kinase
    modules:
      - seq: GAGGGAGGGGCCGGGTCCGCGGCCGGCGAACGGGGCTCGAAGGGTCCTTGTAGCCGGGAATG
      - seq: 5-CTG
      - seq: GGGGGATCACAGACCATTTCTTTCTTTCGGCCAGGCTGAGGCCCTGACGTGGATGGGCAAACT
    prefilter:
      type: SimpleFilter
      seq: 4-CTG
    postfilter:
      - repetitions: 1,3,1
        bases: 5,10,5

  - full_name: SpinAtax1
    description: ATXN1 gén (spinocerebelárna ataxia = SCA1)
    modules:
      - seq: CTCCCAGCTGGAGGCCTATTCCACTCTGCTGGCCAACATGGGCAGTCTGAGCCAGACGCCGGGACACAAGGCTGAG
      - seq: 5-CAG
      - seq: CACCTCAGCAGGGCTCCGGGGCTCATCACCCCGGGGTCCCCCCCACCAGCCCAGCAGAACCAGT
    prefilter:
      type: SimpleFilter
      seq: 4-CAG
    postfilter:
      - repetitions: 1,3,1
        bases: 5,10,5

  - full_name: SpinAtax2
    description: ATXN2 gén (spinocerebelárna ataxia = SCA2)
    modules:
      - seq: TGTCCCCGCCCGGCGTGCGAGCCGGTGTATGGGCCCCTCACCATGTCGCTGAAGCCC
      - seq: 5-CAG
      - seq: CCGCCGCCCGCGGCTGCCAATGTCCGCAAGCCCGGCGGCAGCGGCCTTCTAGCG
    prefilter:
      type: SimpleFilter
      seq: 4-CAG
    postfilter:
      - repetitions: 1,3,1
        bases: 5,10,5

  - full_name: SpinAtax3
    description: ATXN3 gén (spinocerebelárna ataxia = SCA3)
    modules:
      - seq: TCTTTTAAGTTTTGTTTTTTAAATATACTTCACTTTTGAATGTTTCAGACAGCAGCAAAAG
      - seq: 5-CAG
      - seq: GGGGACCTATCAGGACAGAGTTCACATCCATGTGAAAGGCCAGCCACCAGTTCAGGAGCACTTGGGAGTGATCTA
    prefilter:
      type: SimpleFilter
      seq: 4-CAG
    postfilter:
      - repetitions: 1,3,1
        bases: 5,10,5

  - full_name: SpinAtax17
    description: TBP gén (spinocerebelárna ataxia = SCA17)
    modules:
      - seq: CACTGGACTGACCCCACAGCCTATTCAGAACACCAATAGTCTGTCTATTTTGGAAGAGCAACAAAGG
      - seq: 5-CAG
      - seq: GCAGTGGCAGCTGCAGCCGTTCAGCAGTCAACGTCCCAGCAGGCAACACAGGGAACCTCAGGCCAGGCACCACAG
    prefilter:
      type: SimpleFilter
      seq: 4-CAG
    postfilter:
      - repetitions: 1,3,1
        bases: 5,10,5

  - full_name: DRPLA
    description: ATN1 gén (dentatorubral-pallidoluysian atrophy DRPLA)
    modules:
      - seq: CAGGCCCCTTCCCTCCCTCTACTGGGGCCCAGTCCACCGCCCACCCACCAGTCTCAACACATCACCATCACCAC
      - seq: 5-CAG
      - seq: CATCACGGAAACTCTGGGCCCCCTCCTCCTGGAGCATTTCCCCACCCACTGGAGGGCGGTAGCTCCCACCAC
    prefilter:
      type: SimpleFilter
      seq: 4-CAG
    postfilter:
      - repetitions: 1,3,1
        bases: 5,10,5

  - full_name: Huntington2
    description: JPH3 gén (Huntington disease-like 2)
    modules:
      - seq: CTAAGATGCCACCGCATTCGGGGCAGAGCCGGGGCCGGAAGCCAGGGAGCTGC
      - seq: 5-CTG
      - seq: TAAGATGGTTTCTGTGCAGGGAACCTTGGCCGGCTCTGCAGCTGCCCGCCTGCCTGGACTCTCCGATATCCACTCCT
    prefilter:
      type: SimpleFilter
      seq: 4-CTG
    postfilter:
      - repetitions: 1,3,1
        bases: 5,10,5

