channels:
- bioconda
- conda-forge
dependencies:
- python=3.7.10
- numpy=1.20.1
- multiprocess=0.70.11.1
- pysam=0.15.3
- regex=2020.11.13
- numba=0.52.0
- pandas=1.2.2
- scipy=1.6.0
- matplotlib=3.3.4
- pyyaml=5.4.1
# - python-kaleido=0.2.1
- plotly=5.6.0
